### ISSUE TITLE
Sorting Issues

### ISSUE THREAD

**Issue by avengerdba** [DamirPorobic/sbc_backup#1]
When used in linux, the script sorts device128.gz before device99.bz so it deletes the latest config file (not the oldest). So I'd to include other sorting method from this post: 
https://stackoverflow.com/questions/5967500/how-to-correctly-sort-a-string-with-a-number-inside

Proposed change in def cleanUpBackup(dir)

def atoi(text):
    return int(text) if text.isdigit() else text

def natural_keys(text):
    '''
    alist.sort(key=natural_keys) sorts in human order
    http://nedbatchelder.com/blog/200712/human_sorting.html
    (See Toothy's implementation in the comments)
    '''
    return [ atoi(c) for c in re.split(r'(\d+)', text) ]

def cleanUpBackup(dir):
    backups = os.listdir(dir)
    if len(backups) > numberOfBackups:
        logger.info('Number of backups exceeded limit ' + str(len(backups)) + '/' + str(numberOfBackups) )
        backups.sort(key=natural_keys)
        logger.warning('Removing lowest revision number: ' + backups[0])
        os.remove(dir + '/' + backups[0])
    else:
        logger.info('Number of backups within limit ' + str(len(backups)) + '/' + str(numberOfBackups))

**Comment by DamirPorobic** [comment]
Thanks for the feedback. 

Could you create a PR with the proposed change?
